Adding more test scenarios for MessageIntegrationTest
  - Multiple tests fail with `expected:<ERROR> but was:<PING>` and needs to be investigated (commented out for now). It is regarding the following:
    - `should fail to subscribe to group when not a member`.
    - `should receive new message via WebSocket when subscribed`.
    - `should subscribe to group successfully`.
    - `should unsubscribe from group successfully`.
  - Heartbeat runs every fixed seconds which currently interleaves PING messages at any time.
  - Tests expect specific messages but receive PING first (race condition).