Refactoring of WebSocket implementation to use a single WebSocket for multiple groups (#79)
**Note:** Several subscription tests are temporarily commented out due
to a race condition (`expected:<ERROR> but was:<PING>`). The potential
cause is briefly mentioned in
[17de975](https://github.com/SirVingeTheSecond/Japp/pull/79/commits/17de9758663754cbf77f1d9ac0ab77af60ba802a).